"""The 61 upstream rules, read once out of the packaged `data/rules.json`.

This is the only place in the shipped code that knows a rule's severity, title,
description or occurrence suffix. Those five strings are emitted verbatim in
compat output, so a second copy anywhere else is a second source of truth that
no drift check watches; `tests/test_packed_manifest.py` greps `src/` for a
severity literal and fails on one. A rule module asks here.

The JSON is generated by `tools/pack_rules.py` from `upstream/rules-<pin>.json`
and is never hand-edited. It is read through `importlib.resources` rather than
through a path built from `__file__`, because an installed wheel may still be a
zip when it is imported and a directory path into it does not exist.

Stdlib only, deliberately: this module is imported by the registry, by every
rule and by both writers, and the sibling `gtfs-validator` is reachable from
`static/adapter.py` alone.

A missing id raises. Nothing a feed contains can reach this module; rule ids
come from the registry, so an unknown one is a bug in this project rather than a
finding about somebody's data.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import StrEnum
from functools import cache
from importlib import resources
from typing import Any

PACKAGE = "gtfs_rt_validator"
RESOURCE = "data/rules.json"


class Severity(StrEnum):
    """The severity vocabulary, and the only place these words are spelled.

    Upstream declares exactly these two in `ValidationRules.java`, so this is
    not a vocabulary of this project's own invention; it is the packed
    manifest's own value set, given a name so that code which has to *declare* a
    severity can point at it instead of retyping the string.
    `test_declared_severity.py` fails if `data/rules.json` ever carries a
    severity no member here names.

    `Rule.severity` below stays a plain `str`, read from the packed file
    verbatim: coercing it would make the loader assert something about upstream
    that the drift tests already assert, and would turn an upstream change into
    a `ValueError` at import rather than a red drift test.

    Two things declare rather than read: a system error, which is not one of the
    61 and has no entry; and a `spec` or `practice` rule, whose id the manifest
    cannot grow because `data/rules.json` is generated. Both point here, so
    severity keeps one home while its per-rule *choice* lives where that rule's
    other claims about itself live.
    """

    ERROR = "ERROR"
    WARNING = "WARNING"


#: The severity a system error reports at.
#:
#: A system error is not one of upstream's 61 rules, so it has no manifest entry
#: to read a severity from, and the packed manifest cannot grow one: it is
#: generated from `ValidationRules.java` and never hand-edited. It still may not
#: spell the word itself, because severity has one home and this module is it.
#:
#: An earlier version borrowed E001's severity through an exemplar id. That read
#: correctly today and was wrong in principle: if upstream ever downgraded E001,
#: every system error would silently follow a rule it has nothing to do with.
#: The two facts are independent, so they are written down independently.
SYSTEM_ERROR_SEVERITY = Severity.ERROR

__all__ = [
    "SYSTEM_ERROR_SEVERITY",
    "Rule",
    "Severity",
    "all_ids",
    "batch_reachable_ids",
    "emitted_ids",
    "group_order",
    "pin",
    "registration_order",
    "rule",
]


@dataclass(frozen=True, slots=True)
class Rule:
    """One `ValidationRule` constant, as `ValidationRules.java` declares it.

    `occurrence_suffix` is the empty string for W003 upstream, so emptiness is a
    value here rather than a missing field: the writer joins a prefix to nothing
    rather than skipping the half. The human-readable message is
    `prefix + " " + occurrence_suffix`, assembled at write time and never stored
    joined, because upstream's JSON stores the two halves apart.

    `emitters` names the Java validator classes that emit the rule, and is empty
    for the four constants nothing emits. `batch_reachable` is whether any of
    them is one of the nine `BatchProcessor` registers, which is what decides
    the 56 ids compat runs.
    """

    error_id: str
    severity: str
    title: str
    error_description: str
    occurrence_suffix: str
    emitters: tuple[str, ...]
    batch_reachable: bool


@cache
def _packed() -> dict[str, Any]:
    text = resources.files(PACKAGE).joinpath(RESOURCE).read_text(encoding="utf-8")
    return json.loads(text)


@cache
def _rules() -> dict[str, Rule]:
    """Declaration order, which is upstream's own reflective order over the
    declared fields. Python dicts keep insertion order, so the JSON's order is
    the order `all_ids()` reports and the order the writers walk."""
    return {
        rule_id: Rule(
            error_id=record["error_id"],
            severity=record["severity"],
            title=record["title"],
            error_description=record["error_description"],
            occurrence_suffix=record["occurrence_suffix"],
            emitters=tuple(record["emitters"]),
            batch_reachable=record["batch_reachable"],
        )
        for rule_id, record in _packed()["rules"].items()
    }


def rule(rule_id: str) -> Rule:
    try:
        return _rules()[rule_id]
    except KeyError:
        raise KeyError(f"{rule_id} is not a rule upstream declares at pin {pin()[:7]}") from None


def all_ids() -> tuple[str, ...]:
    """Every declared constant, 61 of them, in declaration order."""
    return tuple(_rules())


def emitted_ids() -> tuple[str, ...]:
    """The 57 some validator emits. The other four are declared and dead."""
    return tuple(rule_id for rule_id, record in _rules().items() if record.emitters)


def batch_reachable_ids() -> tuple[str, ...]:
    """The 56 reachable from `BatchProcessor`, which is what compat targets.

    E010 is emitted and not here: its only emitter implements `GtfsFeedValidator`
    and is registered nowhere, so emitting it under `--compat` would itself be a
    parity failure.
    """
    return tuple(rule_id for rule_id, record in _rules().items() if record.batch_reachable)


def registration_order() -> tuple[str, ...]:
    """The nine validators `BatchProcessor` registers, in registration order.

    Output order, not documentation: the runner walks the registry in it and
    compat output is byte-compared.
    """
    return tuple(_packed()["batch_registration_order"])


def group_order() -> dict[str, tuple[str, ...]]:
    """Each registered validator's rule ids, in the order it emits their groups.

    The other half of the output contract `registration_order()` starts.
    Upstream's `validate()` collects occurrences into one list per rule and hands
    those lists to `errors` at its tail, so a group's position is decided by the
    order of those `errors.add(...)` calls and not by when the first occurrence
    was found or by the rule's declaration order. `TimestampValidator` emits its
    three warnings before any of its errors, which is the shape that gives it
    away.

    Nine keys, in registration order. E010's validator is not one of them, for
    the reason `batch_reachable_ids()` gives.
    """
    return {name: tuple(ids) for name, ids in _packed()["group_order"].items()}


def pin() -> str:
    """The upstream commit these rules were read from."""
    return _packed()["pin"]
