"""GENERATED by tools/gen_schema_2015.py. Do not edit.

Source: com.google.transit:gtfs-realtime-bindings:0.0.4, published 2015-02-27,
the artifact upstream compiles against. This is the compat view.
"""

from __future__ import annotations

from gtfs_rt_validator.proto.descriptor import FieldDesc, MessageDesc, Schema

SCHEMA = Schema(
    messages={
        "FeedMessage": MessageDesc(
            "FeedMessage",
            (
                FieldDesc(1, "header", "message", "required", "FeedHeader", None, False),
                FieldDesc(2, "entity", "message", "repeated", "FeedEntity", None, False),
            ),
        ),
        "FeedHeader": MessageDesc(
            "FeedHeader",
            (
                FieldDesc(1, "gtfs_realtime_version", "string", "required", None, "", False),
                FieldDesc(
                    2, "incrementality", "enum", "optional", "FeedHeader.Incrementality", 0, False
                ),
                FieldDesc(3, "timestamp", "uint64", "optional", None, 0, False),
            ),
        ),
        "FeedEntity": MessageDesc(
            "FeedEntity",
            (
                FieldDesc(1, "id", "string", "required", None, "", False),
                FieldDesc(2, "is_deleted", "bool", "optional", None, False, False),
                FieldDesc(3, "trip_update", "message", "optional", "TripUpdate", None, False),
                FieldDesc(4, "vehicle", "message", "optional", "VehiclePosition", None, False),
                FieldDesc(5, "alert", "message", "optional", "Alert", None, False),
            ),
        ),
        "TripUpdate": MessageDesc(
            "TripUpdate",
            (
                FieldDesc(1, "trip", "message", "required", "TripDescriptor", None, False),
                FieldDesc(3, "vehicle", "message", "optional", "VehicleDescriptor", None, False),
                FieldDesc(
                    2,
                    "stop_time_update",
                    "message",
                    "repeated",
                    "TripUpdate.StopTimeUpdate",
                    None,
                    False,
                ),
                FieldDesc(4, "timestamp", "uint64", "optional", None, 0, False),
                FieldDesc(5, "delay", "int32", "optional", None, 0, False),
            ),
        ),
        "TripUpdate.StopTimeEvent": MessageDesc(
            "TripUpdate.StopTimeEvent",
            (
                FieldDesc(1, "delay", "int32", "optional", None, 0, False),
                FieldDesc(2, "time", "int64", "optional", None, 0, False),
                FieldDesc(3, "uncertainty", "int32", "optional", None, 0, False),
            ),
        ),
        "TripUpdate.StopTimeUpdate": MessageDesc(
            "TripUpdate.StopTimeUpdate",
            (
                FieldDesc(1, "stop_sequence", "uint32", "optional", None, 0, False),
                FieldDesc(4, "stop_id", "string", "optional", None, "", False),
                FieldDesc(
                    2, "arrival", "message", "optional", "TripUpdate.StopTimeEvent", None, False
                ),
                FieldDesc(
                    3, "departure", "message", "optional", "TripUpdate.StopTimeEvent", None, False
                ),
                FieldDesc(
                    5,
                    "schedule_relationship",
                    "enum",
                    "optional",
                    "TripUpdate.StopTimeUpdate.ScheduleRelationship",
                    0,
                    False,
                ),
            ),
        ),
        "VehiclePosition": MessageDesc(
            "VehiclePosition",
            (
                FieldDesc(1, "trip", "message", "optional", "TripDescriptor", None, False),
                FieldDesc(8, "vehicle", "message", "optional", "VehicleDescriptor", None, False),
                FieldDesc(2, "position", "message", "optional", "Position", None, False),
                FieldDesc(3, "current_stop_sequence", "uint32", "optional", None, 0, False),
                FieldDesc(7, "stop_id", "string", "optional", None, "", False),
                FieldDesc(
                    4,
                    "current_status",
                    "enum",
                    "optional",
                    "VehiclePosition.VehicleStopStatus",
                    2,
                    False,
                ),
                FieldDesc(5, "timestamp", "uint64", "optional", None, 0, False),
                FieldDesc(
                    6,
                    "congestion_level",
                    "enum",
                    "optional",
                    "VehiclePosition.CongestionLevel",
                    0,
                    False,
                ),
                FieldDesc(
                    9,
                    "occupancy_status",
                    "enum",
                    "optional",
                    "VehiclePosition.OccupancyStatus",
                    0,
                    False,
                ),
            ),
        ),
        "Alert": MessageDesc(
            "Alert",
            (
                FieldDesc(1, "active_period", "message", "repeated", "TimeRange", None, False),
                FieldDesc(
                    5, "informed_entity", "message", "repeated", "EntitySelector", None, False
                ),
                FieldDesc(6, "cause", "enum", "optional", "Alert.Cause", 1, False),
                FieldDesc(7, "effect", "enum", "optional", "Alert.Effect", 8, False),
                FieldDesc(8, "url", "message", "optional", "TranslatedString", None, False),
                FieldDesc(
                    10, "header_text", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(
                    11, "description_text", "message", "optional", "TranslatedString", None, False
                ),
            ),
        ),
        "TimeRange": MessageDesc(
            "TimeRange",
            (
                FieldDesc(1, "start", "uint64", "optional", None, 0, False),
                FieldDesc(2, "end", "uint64", "optional", None, 0, False),
            ),
        ),
        "Position": MessageDesc(
            "Position",
            (
                FieldDesc(1, "latitude", "float", "required", None, 0.0, False),
                FieldDesc(2, "longitude", "float", "required", None, 0.0, False),
                FieldDesc(3, "bearing", "float", "optional", None, 0.0, False),
                FieldDesc(4, "odometer", "double", "optional", None, 0.0, False),
                FieldDesc(5, "speed", "float", "optional", None, 0.0, False),
            ),
        ),
        "TripDescriptor": MessageDesc(
            "TripDescriptor",
            (
                FieldDesc(1, "trip_id", "string", "optional", None, "", False),
                FieldDesc(5, "route_id", "string", "optional", None, "", False),
                FieldDesc(6, "direction_id", "uint32", "optional", None, 0, False),
                FieldDesc(2, "start_time", "string", "optional", None, "", False),
                FieldDesc(3, "start_date", "string", "optional", None, "", False),
                FieldDesc(
                    4,
                    "schedule_relationship",
                    "enum",
                    "optional",
                    "TripDescriptor.ScheduleRelationship",
                    0,
                    False,
                ),
            ),
        ),
        "VehicleDescriptor": MessageDesc(
            "VehicleDescriptor",
            (
                FieldDesc(1, "id", "string", "optional", None, "", False),
                FieldDesc(2, "label", "string", "optional", None, "", False),
                FieldDesc(3, "license_plate", "string", "optional", None, "", False),
            ),
        ),
        "EntitySelector": MessageDesc(
            "EntitySelector",
            (
                FieldDesc(1, "agency_id", "string", "optional", None, "", False),
                FieldDesc(2, "route_id", "string", "optional", None, "", False),
                FieldDesc(3, "route_type", "int32", "optional", None, 0, False),
                FieldDesc(4, "trip", "message", "optional", "TripDescriptor", None, False),
                FieldDesc(5, "stop_id", "string", "optional", None, "", False),
            ),
        ),
        "TranslatedString": MessageDesc(
            "TranslatedString",
            (
                FieldDesc(
                    1,
                    "translation",
                    "message",
                    "repeated",
                    "TranslatedString.Translation",
                    None,
                    False,
                ),
            ),
        ),
        "TranslatedString.Translation": MessageDesc(
            "TranslatedString.Translation",
            (
                FieldDesc(1, "text", "string", "required", None, "", False),
                FieldDesc(2, "language", "string", "optional", None, "", False),
            ),
        ),
    },
    enums={
        "FeedHeader.Incrementality": {"FULL_DATASET": 0, "DIFFERENTIAL": 1},
        "TripUpdate.StopTimeUpdate.ScheduleRelationship": {
            "SCHEDULED": 0,
            "SKIPPED": 1,
            "NO_DATA": 2,
        },
        "VehiclePosition.VehicleStopStatus": {
            "INCOMING_AT": 0,
            "STOPPED_AT": 1,
            "IN_TRANSIT_TO": 2,
        },
        "VehiclePosition.CongestionLevel": {
            "UNKNOWN_CONGESTION_LEVEL": 0,
            "RUNNING_SMOOTHLY": 1,
            "STOP_AND_GO": 2,
            "CONGESTION": 3,
            "SEVERE_CONGESTION": 4,
        },
        "VehiclePosition.OccupancyStatus": {
            "EMPTY": 0,
            "MANY_SEATS_AVAILABLE": 1,
            "FEW_SEATS_AVAILABLE": 2,
            "STANDING_ROOM_ONLY": 3,
            "CRUSHED_STANDING_ROOM_ONLY": 4,
            "FULL": 5,
            "NOT_ACCEPTING_PASSENGERS": 6,
        },
        "Alert.Cause": {
            "UNKNOWN_CAUSE": 1,
            "OTHER_CAUSE": 2,
            "TECHNICAL_PROBLEM": 3,
            "STRIKE": 4,
            "DEMONSTRATION": 5,
            "ACCIDENT": 6,
            "HOLIDAY": 7,
            "WEATHER": 8,
            "MAINTENANCE": 9,
            "CONSTRUCTION": 10,
            "POLICE_ACTIVITY": 11,
            "MEDICAL_EMERGENCY": 12,
        },
        "Alert.Effect": {
            "NO_SERVICE": 1,
            "REDUCED_SERVICE": 2,
            "SIGNIFICANT_DELAYS": 3,
            "DETOUR": 4,
            "ADDITIONAL_SERVICE": 5,
            "MODIFIED_SERVICE": 6,
            "OTHER_EFFECT": 7,
            "UNKNOWN_EFFECT": 8,
            "STOP_MOVED": 9,
        },
        "TripDescriptor.ScheduleRelationship": {
            "SCHEDULED": 0,
            "ADDED": 1,
            "UNSCHEDULED": 2,
            "CANCELED": 3,
        },
    },
    deprecated_enum_values={},
)
