"""GENERATED by tools/gen_schema_current.py. Do not edit.

Source: upstream/gtfs-realtime.proto at the pin in upstream/pins.json.
"""

from __future__ import annotations

from gtfs_rt_validator.proto.descriptor import FieldDesc, MessageDesc, Schema

SCHEMA = Schema(
    messages={
        "FeedMessage": MessageDesc(
            "FeedMessage",
            (
                FieldDesc(1, "header", "message", "required", "FeedHeader", None, False),
                FieldDesc(2, "entity", "message", "repeated", "FeedEntity", None, False),
            ),
        ),
        "FeedHeader": MessageDesc(
            "FeedHeader",
            (
                FieldDesc(1, "gtfs_realtime_version", "string", "required", None, "", False),
                FieldDesc(
                    2, "incrementality", "enum", "optional", "FeedHeader.Incrementality", 0, False
                ),
                FieldDesc(3, "timestamp", "uint64", "optional", None, 0, False),
                FieldDesc(4, "feed_version", "string", "optional", None, "", False),
            ),
        ),
        "FeedEntity": MessageDesc(
            "FeedEntity",
            (
                FieldDesc(1, "id", "string", "required", None, "", False),
                FieldDesc(2, "is_deleted", "bool", "optional", None, False, False),
                FieldDesc(3, "trip_update", "message", "optional", "TripUpdate", None, False),
                FieldDesc(4, "vehicle", "message", "optional", "VehiclePosition", None, False),
                FieldDesc(5, "alert", "message", "optional", "Alert", None, False),
                FieldDesc(6, "shape", "message", "optional", "Shape", None, False),
                FieldDesc(7, "stop", "message", "optional", "Stop", None, False),
                FieldDesc(
                    8, "trip_modifications", "message", "optional", "TripModifications", None, False
                ),
            ),
        ),
        "TripUpdate": MessageDesc(
            "TripUpdate",
            (
                FieldDesc(1, "trip", "message", "required", "TripDescriptor", None, False),
                FieldDesc(3, "vehicle", "message", "optional", "VehicleDescriptor", None, False),
                FieldDesc(
                    2,
                    "stop_time_update",
                    "message",
                    "repeated",
                    "TripUpdate.StopTimeUpdate",
                    None,
                    False,
                ),
                FieldDesc(4, "timestamp", "uint64", "optional", None, 0, False),
                FieldDesc(5, "delay", "int32", "optional", None, 0, False),
                FieldDesc(
                    6,
                    "trip_properties",
                    "message",
                    "optional",
                    "TripUpdate.TripProperties",
                    None,
                    False,
                ),
            ),
        ),
        "TripUpdate.StopTimeEvent": MessageDesc(
            "TripUpdate.StopTimeEvent",
            (
                FieldDesc(1, "delay", "int32", "optional", None, 0, False),
                FieldDesc(2, "time", "int64", "optional", None, 0, False),
                FieldDesc(3, "uncertainty", "int32", "optional", None, 0, False),
                FieldDesc(4, "scheduled_time", "int64", "optional", None, 0, False),
            ),
        ),
        "TripUpdate.StopTimeUpdate": MessageDesc(
            "TripUpdate.StopTimeUpdate",
            (
                FieldDesc(1, "stop_sequence", "uint32", "optional", None, 0, False),
                FieldDesc(4, "stop_id", "string", "optional", None, "", False),
                FieldDesc(
                    2, "arrival", "message", "optional", "TripUpdate.StopTimeEvent", None, False
                ),
                FieldDesc(
                    3, "departure", "message", "optional", "TripUpdate.StopTimeEvent", None, False
                ),
                FieldDesc(
                    7,
                    "departure_occupancy_status",
                    "enum",
                    "optional",
                    "VehiclePosition.OccupancyStatus",
                    0,
                    False,
                ),
                FieldDesc(
                    5,
                    "schedule_relationship",
                    "enum",
                    "optional",
                    "TripUpdate.StopTimeUpdate.ScheduleRelationship",
                    0,
                    False,
                ),
                FieldDesc(
                    6,
                    "stop_time_properties",
                    "message",
                    "optional",
                    "TripUpdate.StopTimeUpdate.StopTimeProperties",
                    None,
                    False,
                ),
            ),
        ),
        "TripUpdate.StopTimeUpdate.StopTimeProperties": MessageDesc(
            "TripUpdate.StopTimeUpdate.StopTimeProperties",
            (
                FieldDesc(1, "assigned_stop_id", "string", "optional", None, "", False),
                FieldDesc(2, "stop_headsign", "string", "optional", None, "", False),
                FieldDesc(
                    3,
                    "pickup_type",
                    "enum",
                    "optional",
                    "TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType",
                    0,
                    False,
                ),
                FieldDesc(
                    4,
                    "drop_off_type",
                    "enum",
                    "optional",
                    "TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType",
                    0,
                    False,
                ),
            ),
        ),
        "TripUpdate.TripProperties": MessageDesc(
            "TripUpdate.TripProperties",
            (
                FieldDesc(1, "trip_id", "string", "optional", None, "", False),
                FieldDesc(2, "start_date", "string", "optional", None, "", False),
                FieldDesc(3, "start_time", "string", "optional", None, "", False),
                FieldDesc(4, "shape_id", "string", "optional", None, "", False),
                FieldDesc(5, "trip_headsign", "string", "optional", None, "", False),
                FieldDesc(6, "trip_short_name", "string", "optional", None, "", False),
            ),
        ),
        "VehiclePosition": MessageDesc(
            "VehiclePosition",
            (
                FieldDesc(1, "trip", "message", "optional", "TripDescriptor", None, False),
                FieldDesc(8, "vehicle", "message", "optional", "VehicleDescriptor", None, False),
                FieldDesc(2, "position", "message", "optional", "Position", None, False),
                FieldDesc(3, "current_stop_sequence", "uint32", "optional", None, 0, False),
                FieldDesc(7, "stop_id", "string", "optional", None, "", False),
                FieldDesc(
                    4,
                    "current_status",
                    "enum",
                    "optional",
                    "VehiclePosition.VehicleStopStatus",
                    2,
                    False,
                ),
                FieldDesc(5, "timestamp", "uint64", "optional", None, 0, False),
                FieldDesc(
                    6,
                    "congestion_level",
                    "enum",
                    "optional",
                    "VehiclePosition.CongestionLevel",
                    0,
                    False,
                ),
                FieldDesc(
                    9,
                    "occupancy_status",
                    "enum",
                    "optional",
                    "VehiclePosition.OccupancyStatus",
                    0,
                    False,
                ),
                FieldDesc(10, "occupancy_percentage", "uint32", "optional", None, 0, False),
                FieldDesc(
                    11,
                    "multi_carriage_details",
                    "message",
                    "repeated",
                    "VehiclePosition.CarriageDetails",
                    None,
                    False,
                ),
            ),
        ),
        "VehiclePosition.CarriageDetails": MessageDesc(
            "VehiclePosition.CarriageDetails",
            (
                FieldDesc(1, "id", "string", "optional", None, "", False),
                FieldDesc(2, "label", "string", "optional", None, "", False),
                FieldDesc(
                    3,
                    "occupancy_status",
                    "enum",
                    "optional",
                    "VehiclePosition.OccupancyStatus",
                    7,
                    False,
                ),
                FieldDesc(4, "occupancy_percentage", "int32", "optional", None, -1, False),
                FieldDesc(5, "carriage_sequence", "uint32", "optional", None, 0, False),
            ),
        ),
        "Alert": MessageDesc(
            "Alert",
            (
                FieldDesc(1, "active_period", "message", "repeated", "TimeRange", None, True),
                FieldDesc(
                    2, "communication_period", "message", "repeated", "TimeRange", None, False
                ),
                FieldDesc(3, "impact_period", "message", "repeated", "TimeRange", None, False),
                FieldDesc(
                    5, "informed_entity", "message", "repeated", "EntitySelector", None, False
                ),
                FieldDesc(6, "cause", "enum", "optional", "Alert.Cause", 1, False),
                FieldDesc(7, "effect", "enum", "optional", "Alert.Effect", 8, False),
                FieldDesc(8, "url", "message", "optional", "TranslatedString", None, False),
                FieldDesc(
                    10, "header_text", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(
                    11, "description_text", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(
                    12, "tts_header_text", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(
                    13,
                    "tts_description_text",
                    "message",
                    "optional",
                    "TranslatedString",
                    None,
                    False,
                ),
                FieldDesc(
                    14, "severity_level", "enum", "optional", "Alert.SeverityLevel", 1, False
                ),
                FieldDesc(15, "image", "message", "optional", "TranslatedImage", None, False),
                FieldDesc(
                    16,
                    "image_alternative_text",
                    "message",
                    "optional",
                    "TranslatedString",
                    None,
                    False,
                ),
                FieldDesc(
                    17, "cause_detail", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(
                    18, "effect_detail", "message", "optional", "TranslatedString", None, False
                ),
            ),
        ),
        "TimeRange": MessageDesc(
            "TimeRange",
            (
                FieldDesc(1, "start", "uint64", "optional", None, 0, False),
                FieldDesc(2, "end", "uint64", "optional", None, 0, False),
            ),
        ),
        "Position": MessageDesc(
            "Position",
            (
                FieldDesc(1, "latitude", "float", "required", None, 0.0, False),
                FieldDesc(2, "longitude", "float", "required", None, 0.0, False),
                FieldDesc(3, "bearing", "float", "optional", None, 0.0, False),
                FieldDesc(4, "odometer", "double", "optional", None, 0.0, False),
                FieldDesc(5, "speed", "float", "optional", None, 0.0, False),
            ),
        ),
        "TripDescriptor": MessageDesc(
            "TripDescriptor",
            (
                FieldDesc(1, "trip_id", "string", "optional", None, "", False),
                FieldDesc(5, "route_id", "string", "optional", None, "", False),
                FieldDesc(6, "direction_id", "uint32", "optional", None, 0, False),
                FieldDesc(2, "start_time", "string", "optional", None, "", False),
                FieldDesc(3, "start_date", "string", "optional", None, "", False),
                FieldDesc(
                    4,
                    "schedule_relationship",
                    "enum",
                    "optional",
                    "TripDescriptor.ScheduleRelationship",
                    0,
                    False,
                ),
                FieldDesc(
                    7,
                    "modified_trip",
                    "message",
                    "optional",
                    "TripDescriptor.ModifiedTripSelector",
                    None,
                    False,
                ),
            ),
        ),
        "TripDescriptor.ModifiedTripSelector": MessageDesc(
            "TripDescriptor.ModifiedTripSelector",
            (
                FieldDesc(1, "modifications_id", "string", "optional", None, "", False),
                FieldDesc(2, "affected_trip_id", "string", "optional", None, "", False),
                FieldDesc(3, "start_time", "string", "optional", None, "", False),
                FieldDesc(4, "start_date", "string", "optional", None, "", False),
            ),
        ),
        "VehicleDescriptor": MessageDesc(
            "VehicleDescriptor",
            (
                FieldDesc(1, "id", "string", "optional", None, "", False),
                FieldDesc(2, "label", "string", "optional", None, "", False),
                FieldDesc(3, "license_plate", "string", "optional", None, "", False),
                FieldDesc(
                    4,
                    "wheelchair_accessible",
                    "enum",
                    "optional",
                    "VehicleDescriptor.WheelchairAccessible",
                    0,
                    False,
                ),
            ),
        ),
        "EntitySelector": MessageDesc(
            "EntitySelector",
            (
                FieldDesc(1, "agency_id", "string", "optional", None, "", False),
                FieldDesc(2, "route_id", "string", "optional", None, "", False),
                FieldDesc(3, "route_type", "int32", "optional", None, 0, False),
                FieldDesc(4, "trip", "message", "optional", "TripDescriptor", None, False),
                FieldDesc(5, "stop_id", "string", "optional", None, "", False),
                FieldDesc(6, "direction_id", "uint32", "optional", None, 0, False),
            ),
        ),
        "TranslatedString": MessageDesc(
            "TranslatedString",
            (
                FieldDesc(
                    1,
                    "translation",
                    "message",
                    "repeated",
                    "TranslatedString.Translation",
                    None,
                    False,
                ),
            ),
        ),
        "TranslatedString.Translation": MessageDesc(
            "TranslatedString.Translation",
            (
                FieldDesc(1, "text", "string", "required", None, "", False),
                FieldDesc(2, "language", "string", "optional", None, "", False),
            ),
        ),
        "TranslatedImage": MessageDesc(
            "TranslatedImage",
            (
                FieldDesc(
                    1,
                    "localized_image",
                    "message",
                    "repeated",
                    "TranslatedImage.LocalizedImage",
                    None,
                    False,
                ),
            ),
        ),
        "TranslatedImage.LocalizedImage": MessageDesc(
            "TranslatedImage.LocalizedImage",
            (
                FieldDesc(1, "url", "string", "required", None, "", False),
                FieldDesc(2, "media_type", "string", "required", None, "", False),
                FieldDesc(3, "language", "string", "optional", None, "", False),
            ),
        ),
        "Shape": MessageDesc(
            "Shape",
            (
                FieldDesc(1, "shape_id", "string", "optional", None, "", False),
                FieldDesc(2, "encoded_polyline", "string", "optional", None, "", False),
            ),
        ),
        "Stop": MessageDesc(
            "Stop",
            (
                FieldDesc(1, "stop_id", "string", "optional", None, "", False),
                FieldDesc(2, "stop_code", "message", "optional", "TranslatedString", None, False),
                FieldDesc(3, "stop_name", "message", "optional", "TranslatedString", None, False),
                FieldDesc(
                    4, "tts_stop_name", "message", "optional", "TranslatedString", None, False
                ),
                FieldDesc(5, "stop_desc", "message", "optional", "TranslatedString", None, False),
                FieldDesc(6, "stop_lat", "float", "optional", None, 0.0, False),
                FieldDesc(7, "stop_lon", "float", "optional", None, 0.0, False),
                FieldDesc(8, "zone_id", "string", "optional", None, "", False),
                FieldDesc(9, "stop_url", "message", "optional", "TranslatedString", None, False),
                FieldDesc(11, "parent_station", "string", "optional", None, "", False),
                FieldDesc(12, "stop_timezone", "string", "optional", None, "", False),
                FieldDesc(
                    13,
                    "wheelchair_boarding",
                    "enum",
                    "optional",
                    "Stop.WheelchairBoarding",
                    0,
                    False,
                ),
                FieldDesc(14, "level_id", "string", "optional", None, "", False),
                FieldDesc(
                    15, "platform_code", "message", "optional", "TranslatedString", None, False
                ),
            ),
        ),
        "TripModifications": MessageDesc(
            "TripModifications",
            (
                FieldDesc(
                    1,
                    "selected_trips",
                    "message",
                    "repeated",
                    "TripModifications.SelectedTrips",
                    None,
                    False,
                ),
                FieldDesc(2, "start_times", "string", "repeated", None, None, False),
                FieldDesc(3, "service_dates", "string", "repeated", None, None, False),
                FieldDesc(
                    4,
                    "modifications",
                    "message",
                    "repeated",
                    "TripModifications.Modification",
                    None,
                    False,
                ),
            ),
        ),
        "TripModifications.Modification": MessageDesc(
            "TripModifications.Modification",
            (
                FieldDesc(
                    1, "start_stop_selector", "message", "optional", "StopSelector", None, False
                ),
                FieldDesc(
                    2, "end_stop_selector", "message", "optional", "StopSelector", None, False
                ),
                FieldDesc(3, "propagated_modification_delay", "int32", "optional", None, 0, False),
                FieldDesc(
                    4, "replacement_stops", "message", "repeated", "ReplacementStop", None, False
                ),
                FieldDesc(5, "service_alert_id", "string", "optional", None, "", False),
                FieldDesc(6, "last_modified_time", "uint64", "optional", None, 0, False),
            ),
        ),
        "TripModifications.SelectedTrips": MessageDesc(
            "TripModifications.SelectedTrips",
            (
                FieldDesc(1, "trip_ids", "string", "repeated", None, None, False),
                FieldDesc(2, "shape_id", "string", "optional", None, "", False),
            ),
        ),
        "StopSelector": MessageDesc(
            "StopSelector",
            (
                FieldDesc(1, "stop_sequence", "uint32", "optional", None, 0, False),
                FieldDesc(2, "stop_id", "string", "optional", None, "", False),
            ),
        ),
        "ReplacementStop": MessageDesc(
            "ReplacementStop",
            (
                FieldDesc(1, "travel_time_to_stop", "int32", "optional", None, 0, False),
                FieldDesc(2, "stop_id", "string", "optional", None, "", False),
            ),
        ),
    },
    enums={
        "FeedHeader.Incrementality": {"FULL_DATASET": 0, "DIFFERENTIAL": 1},
        "TripUpdate.StopTimeUpdate.ScheduleRelationship": {
            "SCHEDULED": 0,
            "SKIPPED": 1,
            "NO_DATA": 2,
            "UNSCHEDULED": 3,
        },
        "TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType": {
            "REGULAR": 0,
            "NONE": 1,
            "PHONE_AGENCY": 2,
            "COORDINATE_WITH_DRIVER": 3,
        },
        "VehiclePosition.VehicleStopStatus": {
            "INCOMING_AT": 0,
            "STOPPED_AT": 1,
            "IN_TRANSIT_TO": 2,
        },
        "VehiclePosition.CongestionLevel": {
            "UNKNOWN_CONGESTION_LEVEL": 0,
            "RUNNING_SMOOTHLY": 1,
            "STOP_AND_GO": 2,
            "CONGESTION": 3,
            "SEVERE_CONGESTION": 4,
        },
        "VehiclePosition.OccupancyStatus": {
            "EMPTY": 0,
            "MANY_SEATS_AVAILABLE": 1,
            "FEW_SEATS_AVAILABLE": 2,
            "STANDING_ROOM_ONLY": 3,
            "CRUSHED_STANDING_ROOM_ONLY": 4,
            "FULL": 5,
            "NOT_ACCEPTING_PASSENGERS": 6,
            "NO_DATA_AVAILABLE": 7,
            "NOT_BOARDABLE": 8,
        },
        "Alert.Cause": {
            "UNKNOWN_CAUSE": 1,
            "OTHER_CAUSE": 2,
            "TECHNICAL_PROBLEM": 3,
            "STRIKE": 4,
            "DEMONSTRATION": 5,
            "ACCIDENT": 6,
            "HOLIDAY": 7,
            "WEATHER": 8,
            "MAINTENANCE": 9,
            "CONSTRUCTION": 10,
            "POLICE_ACTIVITY": 11,
            "MEDICAL_EMERGENCY": 12,
            "SPECIAL_EVENT": 13,
        },
        "Alert.Effect": {
            "NO_SERVICE": 1,
            "REDUCED_SERVICE": 2,
            "SIGNIFICANT_DELAYS": 3,
            "DETOUR": 4,
            "ADDITIONAL_SERVICE": 5,
            "MODIFIED_SERVICE": 6,
            "OTHER_EFFECT": 7,
            "UNKNOWN_EFFECT": 8,
            "STOP_MOVED": 9,
            "NO_EFFECT": 10,
            "ACCESSIBILITY_ISSUE": 11,
        },
        "Alert.SeverityLevel": {"UNKNOWN_SEVERITY": 1, "INFO": 2, "WARNING": 3, "SEVERE": 4},
        "TripDescriptor.ScheduleRelationship": {
            "SCHEDULED": 0,
            "ADDED": 1,
            "UNSCHEDULED": 2,
            "CANCELED": 3,
            "REPLACEMENT": 5,
            "DUPLICATED": 6,
            "DELETED": 7,
            "NEW": 8,
        },
        "VehicleDescriptor.WheelchairAccessible": {
            "NO_VALUE": 0,
            "UNKNOWN": 1,
            "WHEELCHAIR_ACCESSIBLE": 2,
            "WHEELCHAIR_INACCESSIBLE": 3,
        },
        "Stop.WheelchairBoarding": {"UNKNOWN": 0, "AVAILABLE": 1, "NOT_AVAILABLE": 2},
    },
    deprecated_enum_values={
        "TripDescriptor.ScheduleRelationship": ("ADDED",),
    },
)
